### ISSUE TITLE
Bug Menu pada Opensid 2.9

### ISSUE THREAD

**Issue by balongbesuk** [batudaa/batudaa-theme#3]
Bug Menu pada Opensid 2.9

![img12](https://user-images.githubusercontent.com/35319600/35683043-47ddbe86-0795-11e8-981e-68e4067725df.jpg)

**Comment by batudaa** [comment]
Sejak versi pasca-2.8 ternyata ada perubahan pada bagian menu. 
Perbaikan sudah ada pada rilis baru. Silahkan download dan diupgrade.

Thank's

**Comment by Faizin88** [comment]
Terima Kasih.. Tema Batudaa sangat bagus.. dan sangat membantu bagi desa kami.

**Comment by Faizin88** [comment]
Izin Download
