### ISSUE TITLE
Aplikasi tema

### ISSUE THREAD

**Issue by haqi89** [batudaa/batudaa-theme#6]
Mau diaplikasikan ke web koq error505 y bang,,mhon pencerhannya 🙏

**Comment by batudaa** [comment]
505 HTTP Version Not Supported?
Dihalaman apa muncul pesan itu?

**Comment by haqi89** [comment]
Ada petunjuk intalan utk theme batudaa bang??

**Comment by haqi89** [comment]
![error](https://user-images.githubusercontent.com/44763080/56017133-8ef4e580-5d28-11e9-82ca-bb0177c4e641.png)

**Comment by haqi89** [comment]
Unable to load the requested file: ../../themes/batudaa/template.php

Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.
